--- 
- name: print project list
  hosts: all
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
    tower_url: "https://localhost"
    tower_username: "username"
    tower_password: "password"

  collections:
    - ansible.controller
  tasks:
    - name: debug ansible_playbook_python
      debug:
        msg: "{{ ansible_playbook_python }}"

    - name: retrieve all projects from Tower
      ansible.controller.tower_export:
        all: true
        tower_host: "{{ tower_url }}"
        tower_username: "{{ tower_username }}"
        tower_password: "{{ tower_password }}"
        validate_certs: false
      register: tower_project_list

    - name: debug output
      debug:
        var: tower_project_list
