--- 
- name: print project list
  hosts: all
  vars:
    ansible_python_interpreter: "{{ ansible_playbook_python }}"
  collections:
    - ansible.controller
  tasks:
    - name: debug ansible_playbook_python
      debug:
        msg: "{{ ansible_playbook_python }}"

    - name: retrieve all projects from Tower
      ansible.controller.tower_export:
        all: true
        tower_host: "https://localhost"
        tower_username: "{{ lookup('env', 'TOWER_USERNAME') }}"
        tower_password: "{{ lookup('env', 'TOWER_PASSWORD') }}"
        validate_certs: false
      register: tower_project_list

    - name: debug output
      debug:
        var: tower_project_list
